export const surpriseMePrompts = [
  "A serene mountain landscape during sunrise with misty clouds",
  "A bustling futuristic city skyline with flying cars and neon lights",
  "An enchanted forest with glowing plants and magical creatures",
  "A cozy winter cabin in a snowy forest under the northern lights",
  "A vintage 1950s diner with classic cars parked outside",
  "A peaceful beach scene with clear blue water and palm trees",
  "A desert landscape with a lone cactus and a colorful sunset",
  "A mystical waterfall in the heart of a dense jungle",
  "A futuristic space station orbiting a distant planet",
  "A quiet village street scene in autumn with falling leaves",
  "An underwater scene with colorful coral reefs and tropical fish",
  "A dramatic mountain range with clouds and rays of sunlight",
  "A medieval castle on a cliff surrounded by fog",
  "A city park in spring with cherry blossom trees in full bloom",
  "A rustic farmhouse with a field of sunflowers in the background",
  "A snowy mountain landscape with a skier going downhill",
  "A dense rainforest with rays of sunlight streaming through the trees",
  "A close-up of a beautiful butterfly on a flower",
  "A fantasy dragon flying over a medieval village",
  "A classic Victorian mansion with a garden of roses",
  "A cat lounging by a window with a rainy cityscape outside",
  "An astronaut floating in space with Earth in the background",
  "A magical portal opening in a dark forest",
  "A pirate ship sailing on the open sea under a starry sky",
  "A vibrant city street market with various colorful stalls",
  "A lone wolf howling at the full moon in a forest",
  "A futuristic robot in a neon-lit alleyway",
  "A peaceful Japanese garden with a koi pond and bridge",
  "A luxurious yacht on a calm turquoise sea",
  "A vibrant underwater coral reef with various sea creatures",
  "A classic steam locomotive crossing a bridge over a canyon",
  "A magical library with floating books and glowing lights",
  "A young wizard practicing spells in a forest",
  "An ancient ruin in a dense jungle, partially overgrown with vines",
  "A peaceful lakeside scene with ducks swimming at sunset",
  "A superhero flying over a modern cityscape",
  "A quaint small-town bakery with pastries displayed outside",
  "A cozy reading nook with a cat sleeping on a chair",
  "A fantasy castle floating among clouds",
  "A dragon curled up in a cave with piles of treasure",
  "A mysterious island with a hidden waterfall",
  "A vibrant festival scene with colorful lights and fireworks",
  "A lonely lighthouse on a rocky coast at dusk",
  "A futuristic flying car zooming through a high-tech city",
  "A serene meadow with wildflowers and a butterfly",
  "A space explorer discovering a new alien world",
  "A hot air balloon floating over a scenic countryside",
  "A spaceship landing on a barren alien planet",
  "A cozy village market square at Christmastime",
  "A mysterious enchanted forest with glowing mushrooms"
];
